# Generated by Django 3.2 on 2021-04-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('pair', models.CharField(max_length=10)),
                ('mms_20', models.FloatField()),
                ('mms_50', models.FloatField()),
                ('mms_200', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'coins',
            },
        ),
        migrations.AddConstraint(
            model_name='coin',
            constraint=models.UniqueConstraint(fields=('timestamp', 'pair'), name='unique_entry'),
        ),
    ]
